version: '2'
services:
 store_commit_messages: 
   build: .
   container_name: store_commit_messages
   environment:
    - LOG_LEVEL=INFO
   volumes:
   - .:/app
   extra_hosts:
   - "db.mongodb.priceboard.in:172.17.0.1"
   command: sh -c 'git add . && git commit -m "success message stored"'

