version: '2'
services:
 store_commit_messages: 
   build: .
   container_name: store_commit_messages

   environment:
    - LOG_LEVEL=DEBUG
   volumes:
   - .:/app
   extra_hosts:
   - "db.mongodb.priceboard.in:172.17.0.1"
   command: sh -c 'ls && git add . && git commit -m "data stored again" && git push origin master'

